{% set name = "ecmwf-api-client" %}
{% set version = "1.6.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 1fc0eba27163686b7fba5da027cc5dc0a361f75b652508fa7805f50599368b1c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - ecmwfapi

about:
  home: https://software.ecmwf.int/wiki/display/WEBAPI
  license: Apache-2.0
  license_file: LICENSE
  summary: Python client for ECMWF web services API.

extra:
  recipe-maintainers:
    - Ohjeah
    - avalentino
