{% set name = "ecmwf-api-client" %}
{% set version = "1.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ad52f07dbf132b1dcf710096a670447b821944ec969e683e40838eec6e0516b9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - python >=3.6

test:
  imports:
    - ecmwfapi

about:
  home: https://software.ecmwf.int/wiki/display/WEBAPI
  license: Apache-2.0
  license_file: LICENSE
  summary: Python client for ECMWF web services API.

extra:
  recipe-maintainers:
    - Ohjeah
    - avalentino
